server:
  port: 8080
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  #  表的前缀
  # global-config:
  ##    db-config:
  ##      table-prefix: t_
  global-config:
    db-config:
    #            id自动生成策略
  #      id-type: auto
  #    配置类型别名
      type-aliases-package: com.rbq.mybatisplus.mapper
      type-enums-package: com.rbq.mybatisplus.enums